django/apps/blog/urls.py
#!/usr/bin/env python3 
# coding=utf-8

"""
History:
2019/12/9 14:35 : Created by zhaohongwei 
"""

__author__ = "zhaohongwei"
__email__ = "hongweifuture@163.com"
__contact__ = "https://blog.csdn.net/z_johnny"
__version__ = "0.1"
__date__ = "2019/12/9 14:35"
__maintainer__ = "zhaohongwei,"
__description__ = "应用app内路由转发，补充项目urls.py"


from django.urls import path
from .views import IndexView, AboutView, ArticleView, CategoryView, TagView, ArchivesView, BlogSearchView, TimelineView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView, name='about'),
    path('archives/', ArchivesView.as_view(), name='archives'),
    path('article/<slug:slug>', ArticleView.as_view(), name='article'),
    path('category/<slug:slug>', CategoryView.as_view(), name='category'),
    path('tag/<slug:slug>', TagView.as_view(), name='tag'),
    path('timeline/', TimelineView.as_view(), name='timeline'),
    path('search/', BlogSearchView.as_view(), name='search'),

]

django/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('administrator/', admin.site.urls),
    path('',  include(('blog.urls', 'blog'), namespace='blog')),
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/apps/blog/models.py
from django.db import models
from django.shortcuts import reverse
# 支持markdown，富文本编译器django-mdeditor
from mdeditor.fields import MDTextField
import markdown
# django-uuslug将slug自动将中文转换为拼音
from uuslug import uuslug

class Category(models.Model):
    """
    文章分类
    """
    name = models.CharField(max_length=30, verbose_name='文章分类')
    # slug 是唯一的字段，不能出现重复 slug，所以 SlugField 的属性是 unique=True， 可设置最大值, max_length=255
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})

class Tag(models.Model):
    '''
    文章标签
    '''
    name = models.CharField(max_length=30, verbose_name='文章标签')
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag', kwargs={'slug': self.slug})

class Article(models.Model):
    """
    文章标题、摘要、内容、封面图片、创建时间、修改时间、分类、标签、浏览量、是否置顶
    """

    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField(
        max_length=230,
        default='文章摘要等同于网页description内容，请务必填写...',
        verbose_name='文章摘要')
    # 文章内容，使用django-mdeditor插件可实现markdown在线编辑与实时预览
    # body = models.TextField(verbose_name='文章内容')
    body = MDTextField(verbose_name='文章内容')
    # 文章默认缩略图
    img_link = models.ImageField(upload_to='images/%Y-%m', max_length=255,
                                 help_text='提示：不添加封面可以不选择图片，默认没有图片',
                                 blank=True, null=True, verbose_name='文章封面')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    category = models.ForeignKey(Category, verbose_name='文章分类', on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, verbose_name='文章标签')
    views = models.IntegerField(verbose_name='浏览量', default=0)
    is_top = models.BooleanField(verbose_name='置顶', default=False, help_text='勾选即为置顶')
    # 使用uuslug插件，自动化将标题进行拼音化分割
    slug = models.CharField(max_length=35)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.title, instance=self)
        super().save(*args, **kwargs)

class About(models.Model):
    """
    关于
    """
    body = MDTextField(verbose_name='关于')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)

    class Meta:
        verbose_name = '关于'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.body


class FriendLink(models.Model):
    """
    友链
    """
    name = models.CharField(verbose_name='友链名称', max_length=50)
    description = models.CharField(verbose_name='友链描述', max_length=100, blank=True)
    link = models.URLField(verbose_name='友链地址', help_text='请填写http或https开头的完整形式地址')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    is_show = models.BooleanField(verbose_name='是否展示', default=True, help_text='选中表明展示')

    class Meta:
        verbose_name = '友链'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

    def __str__(self):
        return self.name


class Timeline(models.Model):
    """
    时间线 From：https://github.com/Hopetree/izone/blob/master/apps/blog/models.py
    """
    COLOR_CHOICE = (
        ('primary', '基本-蓝色'),
        ('success', '成功-绿色'),
        ('info', '信息-天蓝色'),
        ('warning', '警告-橙色'),
        ('danger', '危险-红色')
    )
    SIDE_CHOICE = (
        ('L', '左边'),
        ('R', '右边'),
    )
    STAR_NUM = (
        (1, '1颗星'),
        (2, '2颗星'),
        (3, '3颗星'),
        (4, '4颗星'),
        (5, '5颗星'),
    )

    side = models.CharField(verbose_name='位置', max_length=1, choices=SIDE_CHOICE, default='L')
    star_num = models.IntegerField(verbose_name='星星个数', choices=STAR_NUM, default=3)
    icon = models.CharField(verbose_name='图标', max_length=50, default='fa fa-pencil')
    icon_color = models.CharField(verbose_name='图标颜色', max_length=20, choices=COLOR_CHOICE, default='info')
    title = models.CharField(verbose_name='标题', max_length=100)
    update_date = models.DateTimeField(verbose_name='更新时间')
    content = MDTextField(verbose_name='主要内容')

    class Meta:
        verbose_name = '时间轴'
        verbose_name_plural = verbose_name
        ordering = ['update_date']

    def __str__(self):
        return self.title[:20]

    def content_to_markdown(self):
        return markdown.markdown(self.content,
                                 extensions=['markdown.extensions.extra', ]
                                 )

django/apps/blog/views.py
from .models import Article, Category, Tag, About, Timeline
from django.shortcuts import get_object_or_404
from django.conf import settings
import time
# 使用 CBV（class base views），在视图里使用类处理请求
from django.shortcuts import render
# 使用 FBV（function base views），在视图里使用函数处理请求
from django.views.generic import ListView, DetailView
# 支持markdown，优化目录和瞄点
import markdown
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
# django-haystack 搜索
from haystack.generic_views import SearchView
# from haystack.views import SearchView
from haystack.query import SearchQuerySet

class IndexView(ListView):
    """
        首页视图,继承自ListVIew，用于展示从数据库中获取的文章列表
    """
    # 获取数据库中的文章列表
    model = Article
    # 指定渲染使用的模板
    template_name = 'blog/index.html'
    # 上下文变量取名，变量传入到模板中
    context_object_name = 'article_index'
    # 分页，每页个数，settings.py中进行设置
    paginate_by = settings.BLOG_INDEX_PAGINATOR_BY

    # https://www.jianshu.com/p/332406309476
    # https://docs.djangoproject.com/en/1.11/topics/pagination/
    # https://www.cnblogs.com/king-lps/p/7324821.html
    # 相当于CBV中的render，向模板中传递字典
    def get_context_data(self, **kwargs):
        # 首先获得父类生成的传递给模板的字典，字典中含有 paginator、page_obj、is_paginated 三个模板变量
        context = super().get_context_data(**kwargs)

        # paginator 是 Paginator 的一个实例
        paginator = context.get('paginator')
        # page_obj 是 Page 的一个实例
        page = context.get('page_obj')
        # is_paginated 是一个布尔变量，用于表示是否已分页。不足设置的每页数量的数据， is_paginated=False
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中
        context.update(pagination_data)

        # 插入自定义的模板变量，首页滚动条，settings.py中进行设置
        context['index_marquee'] = settings.BLOG_INDEX_MARQUEE

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板
        # 记住此时字典中已有了显示分页导航条所需的数据
        return context

    def pagination_data(self, paginator, page, is_paginated):
        # 如果不足设置的每页数量的数据，则没有分页，无需显示分页导航条，不用任何分页导航条的数据返回一个空的字典
        if not is_paginated:
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 表示第一页页码后是否需要显示省略号
        left_has_more = False

        # 表示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 表示是否需要显示第一页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第一页的页码号，此时就无需再显示第一页的页码号
        # 其它情况下第一页的页码是始终需要显示的。
        first = False

        # 表示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）
            # 获取当前页右边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空）
            # 获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3)
                              if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第一页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第一页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第一页，则需要获取当前页左右两边的连续页码号
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3)
                              if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第一页和第一页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        context = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return context

    # 返回用于queryset排序的一个或多个字段，用来进行“置顶”排序，模板中未成功实现，此方法可行
    # https://github.com/Hopetree/izone/blob/master/apps/blog/views.py
    def get_ordering(self):
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ('-is_top', '-create_date')


class CategoryView(IndexView):
    """
        分类页，继承自Article，只是对应Article的过滤
    """
    def get_queryset(self):
        category = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return super().get_queryset().filter(category=category)
        # return self.model.objects.filter(category=category)

    def get_ordering(self):
        """用来进行“置顶”排序"""
        ordering = super().get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering

class TagView(IndexView):
    """
        标签页，继承自Article，只是对应Article的过滤
    """
    def get_queryset(self):
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        return super().get_queryset().filter(tags=tag)

    def get_ordering(self):
        """用来进行“置顶”排序"""
        ordering = super().get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering

class ArticleView(DetailView):
    """
        文章详情页，支持markdown
    """
    model = Article
    template_name = 'blog/article.html'
    context_object_name = 'article_post'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=None)
        # 设置浏览量增加时间判断,同一篇文章两次浏览超过十分钟才重新统计阅览量,作者浏览忽略
        user = self.request.user
        sessions = self.request.session
        views_key = 'views_article_{}'.format(obj.id)
        views_time = sessions.get(views_key)
        if user.id != obj.id:
            if not views_time:
                obj.increase_views()
                sessions[views_key] = time.time()
            else:
                now_time = time.time()
                t = now_time - views_time
                if t > 60 * 10:
                    obj.increase_views()
                    sessions[views_key] = time.time()

        # 文章可以使用markdown书写，带格式的文章，像csdn写markdown文章一样
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),
        ])
        obj.body = md.convert(obj.body)
        # 判断文章是否有目录，模板中直接实现，下面是另外一种方法
        # m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        # obj.toc = m.group(1) if m is not None else ''
        #{% if obj.toc %}
        # https://juejin.im/post/5d5ddec4f265da038f4812ed
        obj.toc = md.toc
        return obj

class ArchivesView(ListView):
    """
        归档页面
    """
    model = Article
    template_name = 'blog/archives.html'
    context_object_name = 'article_archives'

class TimelineView(ListView):
    """
        时间轴设置，markdown转换放在models中，当前ListView类视图内实现失败
    """
    model = Timeline
    template_name = 'blog/timeline.html'
    context_object_name = 'timeline_list'

class BlogSearchView(SearchView):
    """
        搜索视图内容进行排序，实测search_indexes.py中设置不生效
    """
    template_name = 'blog/search/search.html'
    context_object_name = 'search_list'
    queryset = SearchQuerySet().order_by('-id')

def AboutView(request):
    """
    :param request:
    :return: 关于内容，添加默认值，防止body不存在而报错
    """
    body = About.objects.first()
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
    ])
    # body = obj.md
    if body is None:
        repo_url = 'https://github.com/hongweifuture'
        body = '<li>HONGWEI Github 地址：<a href="{}" target="_blank">{}</a></li>'.format(repo_url, repo_url)
    else:
        body = md.convert(body.body)
    return render(request, 'blog/about.html', context={'body': body})

django/apps/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block content_detail %}

<!--body from views AboutView-->
<header class="blog-post-page-title"></header>

<div class="blog-main-post blog-post-page-box">
    <article class="blog-post-block blog-post-page-content">
<!--        转义safe：把html语言的关键字过滤掉，例如<div>-->
        <section>
            {{ body|safe}}
        </section>
    </article>
</div>
{% endblock %}


{% block sidebar_toc %}
    {% include 'blog/sidebar.html' %}
{% endblock %}

django/apps/blog/templates/blog/archives.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block content_detail %}

<!--article archives, base on post year group-->
<header class="blog-post-page-title"></header>

{% if PROJECT_ON %}
<div class="blog-main-post blog-post-page-box">
      <article class="blog-post-block blog-post-page-content">
        <section class="blog-links-page">
            <h3>{{ PROJECT_TITLE }}</h3>
            <div class="links-block "><br>
                {% for project_title, project_url in PROJECT_ARCHIVES.items %}
                <a href="{{ project_url }}" target="_blank" rel="noopener">{{ project_title }}</a><br>
                {% endfor %}
            </div>
        </section>
      </article>
</div>
{% endif %}

<div class="blog-main-post blog-post-page-box">
    {% regroup article_archives by create_date.year as year_list %}
    {% for article_year in year_list %}
    <article class="blog-post-block blog-post-page-content">
        {% if PROJECT_ON %}
            {% if forloop.first %}
            <section>
                <h3> 文章归档 </h3>
            </section>
            {% endif %}
        {% endif %}
        <h5 class="pl-3">{{ article_year.grouper }} 年</h5>
            {% regroup article_year.list by create_date.month as month_list %}
            {% for article_month in month_list %}
            <h6 class="pl-5" >{{ article_month.grouper }} 月 (共 {{ article_month.list|length }} 篇)  </h6>
                <div class="pl-4 collection">
                    {% for article_day in article_month.list %}
                    <li class="text-info" style="font-size:16px;">{{ article_day.create_date|date:'m-d' }} &nbsp;&nbsp;&nbsp;<a href="{{ article_day.get_absolute_url }}" target="_blank">{{ article_day.title }}</a></li>
                    {% endfor %}
                </div>

            {% endfor %}
    </article>
    {% endfor %}
</div>
{% endblock %}


{% block sidebar_toc %}
    {% include 'blog/sidebar.html' %}
{% endblock %}

django/apps/blog/templates/blog/header.html
<!--blog header, include navigation search-->
<header class="blog-header">
<!--    手机网页-->
    <a href="/" class="blog-header-mobile-title">{{ BLOG_SIDEBAR_TITLE }}</a>
    <a href="javascript:;" class="blog-header-navbar-btn"><i class="fa fa-bars"></i></a>
    <nav class="blog-header-navbar blog-header-fixed">
        <!--navigation-->
        <ul class="blog-navbar-links">

              <li class="blog-nav-item"><a href="/" class="transition">首页</a></li>

              <li class="blog-nav-item"><a href="/archives/" class="transition">归档</a></li>

<!--              <li class="blog-nav-item"><a href="/timeline/" class="transition">时间线</a></li>-->

              <li class="blog-nav-item"><a href="/about/" class="transition">关于</a></li>

            <!--search-->
            <div class="blog-navbar-right">
<!--                {# 下面form表单的method 是'get'不能改变，搜索栏的文本框的name="q" 也是固定不变的 #}-->
<!--                {# action 表单的 提交地址，对搜索的处理 交由 搜索引擎 进行处理 #}-->
                <form method="get" id="searchform" action="{% url 'blog:search' %}">
                    <div class="input-group">
                        <input type="search" class="blog-header-search" placeholder="search..." name="q">
                        <button type="submit" class="blog-header-search-btn"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
        </ul>
    </nav>
</header>

django/apps/blog/templates/blog/sidebar.html
{% load blog_tags %}

<!--blog sidebar-->
<div class="col-xl-3 blog-sidebar">
    <div class="blog-sidebar-title">
        <a href="">{{ BLOG_SIDEBAR_TITLE }}</a>
    </div>
    <div class="blog-sidebar-notice">
        {{ BLOG_SIDEBAR_NOTICE }}
    </div>
    <div class="blog-sidebar-icon blog-sidebar-padding">
        <ul>
            <li><a href="https://github.com/hongweifuture" class="icon-github" target="_blank" data-toggle="tooltip" data-placement="top" title="Github"><i class="fa fa-github"></i></a></li>
            <li><a href="//shang.qq.com/wpa/qunwpa?idkey=1d3aa2df80b07cdbe9369ba07c258d38930388a0dfa109940d252dd46018e1e1" class="icon-qq" target="_blank" data-toggle="tooltip" data-placement="bottom"
                   title="加入QQ群 <img src='{% static 'blog/images/qq-group.png' %}' style='height:150px;width:150px;'>" data-html="true"><i class="fa fa-qq"></i></a></li>

            <li><a href="mailto:i@zhwei.cn" class="icon-email" data-toggle="tooltip" data-placement="top" title="E-Mail"><i class="fa fa-envelope"></i></a></li>
            <li><a href="https://blog.csdn.net/z_johnny" class="icon-csdn" data-toggle="tooltip" target="_blank" data-placement="top" title="CSDN 博客" ><i class="fa fa-bold"></i></a></li>
<!--            <li><a href="" class="icon-rss" data-toggle="tooltip" target="_blank" data-placement="top" title="RSS"><i class="fa fa-rss"></i></a></li>-->

        </ul>
    </div>
    <div class="blog-sidebar-count blog-sidebar-padding">
        <div class="blog-sidebar-count-left">
            {% get_article_list as article_list %}
            <p class="blog-sidebar-count-p">{{ article_list|length }}</p>
            <span class="blog-sidebar-count-span">文章</span>
        </div>
        <div class="blog-sidebar-count-right">
            {% get_tag_list as tag_list %}
            <p class="blog-sidebar-count-p">{{ tag_list|length }}</p>
            <span class="blog-sidebar-count-span">标签</span>
        </div>
        <div style="clear: both;"></div>
    </div>

    <div class="blog-sidebar-categories">
        <h4 class="blog-sidebar-h4"><i class="fa fa-folder-open"></i> 分类 </h4>
        <ul class="list-group blog-sidebar-padding">
            <li class="list-group-item justify-content-between">
                <a href="/timeline/" style="color:coral;text-decoration:none;" target="_blank">博客时间轴</a>
            </li>
            {% get_category_list as categorys %}
            {% for category in categorys %}
            <li class="list-group-item justify-content-between">
            <!-- <a href="{% url 'blog:category' category.slug %}">{{ category.name }}</a>-->
                <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                <span class="badge badge-default badge-pill">{{ category.article_num }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="blog-sidebar-tags">
        <h4 class="blog-sidebar-h4"><i class="fa fa-tag"></i> 标签云 </h4>
        <ul class="blog-sidebar-tags-ul blog-sidebar-padding">
                <!--tag_list has define on line：29-->
                {% for tag in tag_list %}
              <li><a href="{{ tag.get_absolute_url }}" class="tag-could" data-toggle="tooltip" data-placement="top" title="{{ tag.name }}">{{ tag.name }}</a></li>
                {% endfor %}
        </ul>
    </div>
    <div class="blog-sidebar-link">
        <h4 class="blog-sidebar-h4">
            <i class="fa fa-link"></i>友链
            <span data-toggle="modal" data-target="#blog-sideba-friendlink-content">
                <span style="float:right;color: deepskyblue" data-toggle="tooltip" data-placement="top" title='申请友链请点击 "申请" 后扫码联系我~~'>申请</span>
            </span>
            <div class="modal fade" id="blog-sideba-friendlink-content" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">请扫码进行联系</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row blog-sideba-friendlink-content">
                            <!-- 说明：每row行共12列，分个2div，每个div平占6列，即2个*6列=12列 -->
                            <div class="col-md-6">
                                <h5>微信</h5>
                                <img class="blog-sideba-friendlink-img no-lightbox" src="{% static 'blog/images/wechat.png' %}">
                            </div>
                            <div class="col-md-6">
                                <h5>QQ</h5>
                                <img class="blog-sideba-friendlink-img no-lightbox" src="{% static 'blog/images/qq.png' %}">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                    </div>
                </div>
            </div>
            </div>

        </h4>
        {% get_friendlink as FriendLinks %}
        {% for friendlink in FriendLinks %}
        <ul >
            <li><a href="{{ friendlink.link }}" target="_blank" data-toggle="tooltip" data-placement="bottom" title="{{ friendlink.description }}">{{ friendlink.name }}</a></li>
        </ul>
        {% endfor %}


    </div>
    <script>
      // 博客侧栏标签云随机色
      var tag_cloud = $('.tag-could');
      tag_cloud.each(function () {
          var Cnum = 9;
          var Crand = parseInt(Math.random() * Cnum);
          $(this).addClass("tag-could" + Crand);
      })
    </script>


    <!--返回顶部按钮-->
    <div class="retop">
        <i class="fa fa-angle-up"></i>
    </div>
</div>